// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZbG9lrRERw8FA2qxBHrsLiZUR74Jub0U',
    appId: '1:800006844740:web:06fcef768d4603f80e6711',
    messagingSenderId: '800006844740',
    projectId: 'education-apps-ad6c5',
    authDomain: 'education-apps-ad6c5.firebaseapp.com',
    storageBucket: 'education-apps-ad6c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDVVA1yRuN8NspDMheJV2cADB56w3PwMo',
    appId: '1:800006844740:android:bfdd593cf254724c0e6711',
    messagingSenderId: '800006844740',
    projectId: 'education-apps-ad6c5',
    storageBucket: 'education-apps-ad6c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzX1TGuLS6Ha10vkFPROFeyA3jz2aejsI',
    appId: '1:800006844740:ios:73c2f8b8a355c3510e6711',
    messagingSenderId: '800006844740',
    projectId: 'education-apps-ad6c5',
    storageBucket: 'education-apps-ad6c5.appspot.com',
    iosBundleId: 'com.example.educationApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzX1TGuLS6Ha10vkFPROFeyA3jz2aejsI',
    appId: '1:800006844740:ios:73c2f8b8a355c3510e6711',
    messagingSenderId: '800006844740',
    projectId: 'education-apps-ad6c5',
    storageBucket: 'education-apps-ad6c5.appspot.com',
    iosBundleId: 'com.example.educationApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZbG9lrRERw8FA2qxBHrsLiZUR74Jub0U',
    appId: '1:800006844740:web:06291cc11bf528d00e6711',
    messagingSenderId: '800006844740',
    projectId: 'education-apps-ad6c5',
    authDomain: 'education-apps-ad6c5.firebaseapp.com',
    storageBucket: 'education-apps-ad6c5.appspot.com',
  );
}
